// #include "includes/libft/libft.h"
#include <stdio.h>
#include "./src/ft_printf.h"
#include <limits.h>

int main()
{
  printf("%d\n", printf(" %.2d \n", -1));
  printf("%d\n", ft_printf(" %.2d \n", -1));
  printf("%d\n", printf(" %.4d \n", -14));
  printf("%d\n", ft_printf(" %.4d \n", -14));
  printf("%d\n", printf(" %.3d \n", -11));
  printf("%d\n", ft_printf(" %.3d \n", -11));
  printf("%d\n", printf(" %.1d \n", 0));
  printf("%d\n", ft_printf(" %.1d \n", 0));
  // printf("%d\n", printf("%d\n", 1));
  // printf("%d\n", printf("%-d\n", 0));
  // printf("%d\n", ft_printf("%-d\n", 0));
  // long x = 1;
  // printf("%d\n", printf("%d\n", x));
  // printf("%d\n", 0);
  // ft_printf("%d\n", 0);
  // printf("%.d\n", 0);
  // ft_printf("%.d\n", 0);
  // printf("%-5.d\n", 0);
  // ft_printf("%-5.d\n", 0);
  // printf("%d\n", 123);
  // ft_printf("%d\n", 123);
  // printf("%d\n", INT_MAX);
  // ft_printf("%d\n", INT_MAX);
  // printf("%d\n", INT_MIN);
  // ft_printf("%d\n", INT_MIN);
  // printf("%.d\n", 123);
  // ft_printf("%.d\n", 123);
  // printf("%15.5d\n", INT_MAX);
  // ft_printf("%15.5d\n", INT_MAX);
  // printf("%1000.100d\n", INT_MAX);
  // ft_printf("%1000.100d\n", INT_MAX);
  // printf("%4090.100d\n", INT_MAX);
  // ft_printf("%4090.100d\n", INT_MAX);
  // printf("%-29.19d\n", 0);
  // ft_printf("%-29.19d\n", 0);
  // printf("%-29.d\n", 0);
  // ft_printf("%-29.d\n", 0);
  // printf("%0-.32d\n", 123);
  // ft_printf("%0-.32d\n", 123);
  // printf("%#0-.32d\n", 123);
  // ft_printf("%#0-.32d\n", 123);
  // printf("%-+64.32d\n", 123);
  // ft_printf("%-+64.32d\n", 123);
  // printf("%- 64.32d\n", 123);
  // ft_printf("%- 64.32d\n", 123);
  // printf("%-29.19d\n", INT_MIN);
  // ft_printf("%-29.19d\n", INT_MIN);
  // printf("%-29.d\n", INT_MIN);
  // ft_printf("%-29.d\n", INT_MIN);
  // printf("%0-.32d\n", INT_MIN);
  // ft_printf("%0-.32d\n", INT_MIN);
  // printf("%#0-.32d\n", INT_MIN);
  // ft_printf("%#0-.32d\n", INT_MIN);
  // printf("%-+64.32d\n", INT_MIN);
  // ft_printf("%-+64.32d\n", INT_MIN);
  // printf("%- 64.32d\n", INT_MIN);
  // ft_printf("%- 64.32d\n", INT_MIN);
  // printf("%-29.19d\n", INT_MAX);
  // ft_printf("%-29.19d\n", INT_MAX);
  // printf("%-29.d\n", INT_MAX);
  // ft_printf("%-29.d\n", INT_MAX);
  // printf("%0-.32d\n", INT_MAX);
  // ft_printf("%0-.32d\n", INT_MAX);
  // printf("%#0-.32d\n", INT_MAX);
  // ft_printf("%#0-.32d\n", INT_MAX);
  // printf("%-+64.32d\n", INT_MAX);
  // ft_printf("%-+64.32d\n", INT_MAX);
  // printf("%- 64.32d\n", INT_MAX);
  // ft_printf("%- 64.32d\n", INT_MAX);
  // printf("%-29.d\n", LONG_MIN);
  // ft_printf("%-29.d\n", LONG_MIN);
  // printf("%0-.32d\n", LONG_MIN);
  // ft_printf("%0-.32d\n", LONG_MIN);
  // printf("%#0-.32d\n", LONG_MIN);
  // ft_printf("%#0-.32d\n", LONG_MIN);
  // printf("%-+64.32d\n", LONG_MIN);
  // ft_printf("%-+64.32d\n", LONG_MIN);
  // printf("%- 64.32d\n", LONG_MIN);
  // ft_printf("%- 64.32d\n", LONG_MIN);
  // printf("%-29.d\n", LONG_MAX);
  // ft_printf("%-29.d\n", LONG_MAX);
  // printf("%0-.32d\n", LONG_MAX);
  // ft_printf("%0-.32d\n", LONG_MAX);
  // printf("%#0-.32d\n", LONG_MAX);
  // ft_printf("%#0-.32d\n", LONG_MAX);
  // printf("%-+64.32d\n", LONG_MAX);
  // ft_printf("%-+64.32d\n", LONG_MAX);
  // printf("%- 64.32d\n", LONG_MAX);
  // ft_printf("%- 64.32d\n", LONG_MAX);
  // printf("%#-v2\n", 5);
  // ft_printf("%#-v2\n", 5);
  // printf("hellotherefaggot%-29.d\n", LONG_MAX);
  // ft_printf("hellotherefaggot%-29.d\n", LONG_MAX);
  // printf("hehe%0-.32d\n", LONG_MAX);
  // ft_printf("hehe%0-.32d\n", LONG_MAX);
  // printf(" %#0-.32d\n", LONG_MAX);
  // ft_printf(" %#0-.32d\n", LONG_MAX);
  // printf("///%-+64.32d\n", LONG_MAX);
  // ft_printf("///%-+64.32d\n", LONG_MAX);
  // printf("-$%- 64.32d\n", LONG_MAX);
  // ft_printf("-$%- 64.32d\n", LONG_MAX);
}

